!ifndef is_main {
    !src "../../lib/x16.asm"
    *= $801
}

str_white_on_black !pet PET_COLOR_BLACK, PET_COLOR_SWAP, PET_COLOR_WHITE
str_color_score !pet PET_COLOR_DGRAY, PET_COLOR_SWAP, PET_COLOR_YELLOW, PET_NULL

str_press_enter !pet PET_COLOR_BLACK, PET_COLOR_SWAP, PET_COLOR_WHITE,"press enter",PET_COLOR_BLACK,PET_NULL
str_ui_full_row !pet PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK,"                                        ", PET_NULL
str_ui_game_row !pet PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ",PET_COLOR_BLACK, PET_COLOR_SWAP, "                           ", PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK,"            ", PET_NULL
str_ui_score_lbl_row !pet PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ",PET_COLOR_BLACK, PET_COLOR_SWAP, "                           ", PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ", PET_COLOR_DGRAY, PET_COLOR_SWAP, PET_COLOR_WHITE,"  score:  ",PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ", PET_NULL
str_ui_score_val_row !pet PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ",PET_COLOR_BLACK, PET_COLOR_SWAP, "                           ", PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ", PET_COLOR_DGRAY, PET_COLOR_SWAP, PET_COLOR_YELLOW," 00000000 ",PET_COLOR_GRAY, PET_COLOR_SWAP, PET_COLOR_BLACK," ", PET_NULL